import 'package:flutter/material.dart';
import 'package:privacygui_widgets/theme/material/text_scheme_ext.dart';

const linksysTextTheme = TextTheme(
  displayLarge: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w400,
    fontSize: 57,
    decoration: TextDecoration.none,
    height: 64 / 57,
    letterSpacing: -0.25,
    fontFamilyFallback: fontKeys,
  ),
  displayMedium: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w400,
    fontSize: 45,
    decoration: TextDecoration.none,
    height: 52 / 45,
    letterSpacing: 0,
    fontFamilyFallback: fontKeys,
  ),
  displaySmall: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w400,
    fontSize: 36,
    decoration: TextDecoration.none,
    height: 44 / 36,
    letterSpacing: 0,
    fontFamilyFallback: fontKeys,
  ),
  headlineLarge: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w700,
    fontSize: 32,
    decoration: TextDecoration.none,
    height: 40 / 32,
    letterSpacing: 0,
    fontFamilyFallback: fontKeys,
  ),
  headlineMedium: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w700,
    fontSize: 28,
    decoration: TextDecoration.none,
    height: 36 / 28,
    letterSpacing: 0,
    fontFamilyFallback: fontKeys,
  ),
  headlineSmall: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w700,
    fontSize: 24,
    decoration: TextDecoration.none,
    height: 32 / 24,
    letterSpacing: 0,
    fontFamilyFallback: fontKeys,
  ),
  titleLarge: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w700,
    fontSize: 22,
    decoration: TextDecoration.none,
    height: 28 / 22,
    letterSpacing: 0,
    fontFamilyFallback: fontKeys,
  ),
  titleMedium: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w700,
    fontSize: 16,
    decoration: TextDecoration.none,
    height: 24 / 16,
    letterSpacing: 0.15,
    fontFamilyFallback: fontKeys,
  ),
  titleSmall: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w700,
    fontSize: 14,
    decoration: TextDecoration.none,
    height: 20 / 14,
    letterSpacing: 0.1,
    fontFamilyFallback: fontKeys,
  ),
  labelLarge: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w700,
    fontSize: 14,
    decoration: TextDecoration.none,
    height: 20 / 14,
    letterSpacing: 0.1,
    fontFamilyFallback: fontKeys,
  ),
  labelMedium: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w700,
    fontSize: 12,
    decoration: TextDecoration.none,
    height: 16 / 12,
    letterSpacing: 0.5,
    fontFamilyFallback: fontKeys,
  ),
  labelSmall: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w700,
    fontSize: 11,
    decoration: TextDecoration.none,
    height: 16 / 11,
    letterSpacing: 0.5,
    fontFamilyFallback: fontKeys,
  ),
  bodyLarge: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w400,
    fontSize: 16,
    decoration: TextDecoration.none,
    height: 24 / 16,
    letterSpacing: 0,
    fontFamilyFallback: fontKeys,
  ),
  bodyMedium: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w400,
    fontSize: 14,
    decoration: TextDecoration.none,
    height: 20 / 14,
    letterSpacing: 0,
    fontFamilyFallback: fontKeys,
  ),
  bodySmall: TextStyle(
    fontFamily: 'NeueHaasGrotTextRound',
    package: 'privacygui_widgets',
    fontWeight: FontWeight.w400,
    fontSize: 12,
    decoration: TextDecoration.none,
    height: 16 / 12,
    letterSpacing: 0,
    fontFamilyFallback: fontKeys,
  ),
);

const textSchemeExt = TextSchemeExt(
    bodyExtraSmall: TextStyle(
  fontFamily: 'NeueHaasGrotTextRound',
  package: 'privacygui_widgets',
  fontWeight: FontWeight.w400,
  fontSize: 10,
  decoration: TextDecoration.none,
  height: 14 / 10,
  letterSpacing: 0,
  fontFamilyFallback: fontKeys,
));

extension TextThemeUtil on TextTheme {
  List<TextStyle?> values() {
    List<TextStyle?> list = [
      displayLarge,
      displayMedium,
      displaySmall,
      headlineLarge,
      headlineMedium,
      headlineSmall,
      titleLarge,
      titleMedium,
      titleSmall,
      labelLarge,
      labelMedium,
      labelSmall,
      bodyLarge,
      bodyMedium,
      bodySmall,
    ];
    return list..removeWhere((element) => element == null);
  }
}

///
/// Add fonts here is there has more fonts needed.
///
const fontKeys = [
  'NoToSans',
  'NoToSansKR',
  'NoToSansSC',
  'NoToSansAR',
  'NoToSansTh'
];
